### ISSUE TITLE
Service support

### ISSUE THREAD

**Issue by ecthros** [Kkevsterrr/koth#39]
Create a multi step scoring system with plug-ins for individual services. Here's an example for ftp:

1. Get a few points if the computer is up based on icmp. 
2. Get more points if the port is open. 
3. Get more points if a user can log in. 
4. Get full points if we can upload and download a file. 

Make this extensible so other services can easily be added.

**Comment by Kkevsterrr** [comment]
The original plan was to wrap this around nagios for service validation to achieve that

**Comment by Kkevsterrr** [comment]
No longer wrapping around nagios, current plan is to write a small library of dynamically imported service checkers
